# Generated by Django 3.0.6 on 2020-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_time',
            field=models.TextField(default=''),
        ),
    ]
